### PR TITLE
Make Picamera2.start() create the event loop automatically

### PR DESCRIPTION
**Pull request by davidplowman**
This saves user's scripts from having to remember, but it does mean
that if you want a preview window, you should create it before
calling Picamera2.start().

Signed-off-by: David Plowman <david.plowman@raspberrypi.com>

### CODE REVIEW

**Comment by davidplowman** [comment]
Still not sure about this. It replaces the awkwardness where you _have_ to call `start_preview` with the awkwardness that you sometimes _don't_ have to call `start_preview`...

**Comment by meawoppl** [comment]
I for one think this is great. That said, my application is headless :stuck_out_tongue:

**Comment by davidplowman** [comment]
Well, I think there seems to be a general consensus here slightly in favour of this change. @chrisruk Do you have any opinion either way?

**Comment by chrisruk** [comment]
Yup, I'm happy with not having to manually call start_preview.

**Pull request merged**
