### PR TITLE
Create `formats.py` from dangling @classmethods

### PR DESCRIPTION
**Pull request by meawoppl**
These were attached to the `picamera2` object but used largely externally.

I changed the internal implementation to using `set()` primitives as membership testing is slightly faster that way.

### CODE REVIEW

**Comment by meawoppl** [comment]
Blocked on testing being brokn.

**Comment by davidplowman** [comment]
Closing in order to re-open so that the tests run again.

**Comment by meawoppl** [comment]
Ready @davidplowman and @chrisruk

**Comment by davidplowman** [comment]
Thanks for this PR, I think that's a nice tidy-up. I've tweaked just a couple of things and merged it directly. Thanks!

**Pull request closed without merging**
