### PR TITLE
Fix for MJPEG Server and test case

### PR DESCRIPTION
**Pull request by chrisruk**

### CODE REVIEW

**Comment by davidplowman** [comment]
(This is a fix for https://github.com/raspberrypi/picamera2/issues/361)

@chrisruk Looks good, is there anything else to think about or are we good to merge?

**Comment by chrisruk** [comment]
Just seeing if I can also add a fix for https://github.com/raspberrypi/picamera2/issues/351 too, where timestamps are currently not being added to the file (also mjpeg related)

**Comment by davidplowman** [comment]
OK, cool, I'll merge this one then and wait to hear from you before I make up a 0.3.5 release.

**Comment by chrisruk** [comment]
Okey doke, sounds good

**Pull request merged**
