### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by davidplowman**
I've created some issue templates in order to make reporting and tracking easier. We have:

Bug reports
Suggestions or feature requests
How-To questions
And all other types of issue.

### CODE REVIEW

**Comment by tvoverbeek** [comment]
What about a separate category for documentation?
Case in point: The README for the Tensorflow examples contains the old build instructions, should be updated to follow the main README.

**Comment by davidplowman** [comment]
Yes, documentation is an interesting question.

So the plan is that the documentation here in the repository is basically going to vanish. Maybe just a few things will remain, a link to the new documentation, the contribution guidelines and so on.

Then there'll be a proper "Picamera2 Manual" written from scratch that will be much more extensive than what's here now. Once that exists we'll make sure we have some way to report errors in it, maybe that will be issues here. Do you think it's worth having a documentation category in the interim for the old readme? I'm not sure. I suppose it would stop people wondering why there's no documentation category...!

I note that you're right about that tensorflow readme, though. It's quite out-of-date and actually wrong in many respects. It probably just wants deleting because everything is covered in the main readme.

Thanks!

**Comment by tvoverbeek** [comment]
> Do you think it's worth having a documentation category in the interim for the old readme? I'm not sure.

Agreed. My suggestion was triggered by the outdated Tensorflow README.
Will the official documentation have its own repository or be part of the overall documentation repository?

I guess in the interim we could report those type of issues in the 'Other' category.

**Comment by davidplowman** [comment]
> My suggestion was triggered by the outdated Tensorflow README. 

There's now a PR to get rid of that, so thanks for pointing it out!

>Will the official documentation have its own repository or be part of the overall documentation repository?

That's up to the documentation overlords, of whom I am not one... hopefully I'll know more soon.

**Comment by chrisruk** [comment]
@davidplowman They all look good to me, I think keeping an issue to a single item makes a lot of sense.  Happy for me to merge now?

**Pull request merged**
