### PR TITLE
add socketoutput, capable of splitting packets for datagram socket

### PR DESCRIPTION
**Pull request by CorvetteCole**
This has not been tested yet. Basically, we initialize this very similarly to the FileOutput, but there is one important difference. The socket must be open before this output is started. This is intended to solve https://github.com/raspberrypi/picamera2/issues/313

### CODE REVIEW

**Comment by davidplowman** [comment]
Thanks for posting this.

@chrisruk Is this the kind of thing you think we're looking for?

My initial observation was that the new class might be duplicating a lot of the FileOutput code? Could we derive it from FileOutput instead?

Obviously there would be some further work in tidying the commits, adding some tests and so on, but that is secondary at this point. @CorvetteCole You might want to check our [contribution guidelines](https://github.com/raspberrypi/picamera2#contributing) if you haven't done so, I don't think there's anything surprising or scary in them, but always best to be on the same page!

Thanks!

**Comment by chrisruk** [comment]
Yeah I think it makes sense to extend or modify the FileOutput class.

I did just think we could have something like a split parameter in FileOutput constructor, which could default to 0, for no splitting of data. Then if you set it to 65507, it would split a frame into chunks of 65507 or less.

**Comment by chrisruk** [comment]
Yeah that would be nice, I had a little look into if we could do that, but it seems .makefile creates something like a bufferedreader, so you can't detect that it's got a UDP socket behind it as far as I can tell.

**Comment by davidplowman** [comment]
I think you can do
```
stream = sock.makefile("wb")
print(stream.raw._sock)
```
Bit ugly, though!!

**Comment by chrisruk** [comment]
Cool, didn't know you could do that.  Which would mean we could potentially modify FileOutput to something like this -

```
    def _write(self, frame, timestamp=None):
        try:
            if isinstance(self._fileoutput.raw, socket.SocketIO) and \
                self._fileoutput.raw._sock.type == socket.SocketKind.SOCK_DGRAM:
                # split data here, calling self._fileoutput.write on each chunk
            else:
                self._fileoutput.write(frame)
```

**Comment by davidplowman** [comment]
Indeed, I'd be slightly tempted to do the detection only once in the constructor (and set a `split` variable/property), but otherwise yes!

**Comment by CorvetteCole** [comment]
I agree, this class is very much a duplicate of FileOutput. A split parameter in FileOutput sounds pretty nice for preventing duplicate code.

I personally am in favor of automatically detecting datagram streams, although we would have to be careful in case a passed in file object is not a socket type and doesn't have the _sock attribute. I guess we can wrap that in a try except, thoughts?

The alternative may be to implement the SocketOutput as a subclass of FileOutput and then override some methods, if it would be desirable to separate those. 

Ultimately I ask these questions because I am a little unclear on the architectural goals around these outputs. The purpose of this SocketOutput was _mostly_ just intended to spark some discussion.

Side note: I have read the contribution guidelines... thanks! I've been working super closely integrating this project, so I'd be remiss not to contribute back :)

**Comment by chrisruk** [comment]
> I personally am in favor of automatically detecting datagram streams, although we would have to be careful in case a passed in file object is not a socket type and doesn't have the _sock attribute.

Good point, I believe the following line should then mean _sock must be present-
```
isinstance(self._fileoutput.raw, socket.SocketIO)
```
Python does also have hasattr() to check an attribute is present.

Also that's a good point @davidplowman re. doing the checking in the constructor.

So I think it should be possible to make FileOutput do the splitting of data for us, if a datagram socket is passed even though
it's abstracted somewhat via .makefile(), which means the existing UDP example would work for higher bitrates/resolutions.

**Comment by CorvetteCole** [comment]
I'll see if I can give this a go on my test setup Friday. Will leave this PR open until I or one of you file a new PR for the revised FileOutput. Alternatively, I might just overwrite this PR's contents entirely.

**Comment by chrisruk** [comment]
Thanks everyone for the comments, I've just created a revised FileOutput here - https://github.com/raspberrypi/picamera2/pull/317

**Comment by davidplowman** [comment]
Thanks for all the discussion on this one - I'll close it now in favour of Chris's new PR!

**Pull request closed without merging**
