### PR TITLE
Reflow Init Logic

### PR DESCRIPTION
**Pull request by meawoppl**
Some small work to make the init logic more clear and concise.

### CODE REVIEW

**Comment by chrisruk** [comment]
Just noticed the smoke tests seem to be failing here, you can run the tests locally from the repo doing the following with X running -

```
python3.9 tools/run_tests.py -p $(pwd)
```

And there's also a git hook mentioned in the readme, that will run the style checker which is rather handy

**Comment by meawoppl** [comment]
In all honesty, I have been using the runner attached to this repo as a sort of CI system. I am setting up a small rack of pi4b's later next week with various attached cameras, but until then, opening PR's is the easiest way to run tests.

**Comment by meawoppl** [comment]
@chrisruk also, the linter has somewhat inconsistent behaviour compared to my local run. It seems to want slightly unusual spacing around type hints specifically compared to the usual associated PEP8 style.

**Comment by meawoppl** [comment]
@chrisruk I fixed the lint/style issues as well as the logic that was preventing startup. Its probably out of scope for this change, but the (non-zero) return code for`camera.acquire()` tells whether there camera isn't connected or is held by another process, which seems very useful from a user perspective.

**Comment by meawoppl** [comment]
@chrisruk Conflict resolved, updated to the current `next` commit changed to match request.

**Comment by meawoppl** [comment]
@chrisruk @davidplowman Need anything else here?

**Comment by davidplowman** [comment]
Thanks for the updates. I've merged this directly now with just a small update to the commit message.

**Pull request closed without merging**
