### PR TITLE
Create capture_images_by_key.py

### PR DESCRIPTION
**Pull request by Petros626**
I just created a simple example to take pictures with the keyboard. If there's any issue on performance or anything else, tell me.

Hope it helps some people, if you searched something like this.

### CODE REVIEW

**Comment by Petros626** [comment]
Thanks for watching over, if you got any suggestions how to improve it let me know. How would a non-blocking look like

**Comment by tvoverbeek** [comment]
Tricky depending on if you are running headless or from a terminal window on the desktop.
Search for packages like `keyboard` and `pynput` on PyPi.

**Comment by tvoverbeek** [comment]
@Petros626 I do not have commit permission and am  a 'normal' user just like you. Check with @davidplowman and/or @chrisruk

**Comment by davidplowman** [comment]
Hi, sorry, it sounded from the above like you were still wanting to make the keypress non-blocking? I would agree that this would seem like the behaviour people would mostly expect? But please let me know.

Thanks for adding the sign-off. Could you squash everything into a single commit - wherever we can (it's not always possible of course), we prefer to have single easy-to-understand commits rather than seeing all the trial and error that led to the finished version! Thanks.

**Comment by Petros626** [comment]
@davidplowman Now it's fine and I squashed all the commits in one.

**Comment by davidplowman** [comment]
Hi, I'll have a look at the test failure, it looks like an intermittent problem related to a previous commit.

Would you be OK to look at the flake8 complaints? I think they're probably very trivial. Thanks!

**Comment by Petros626** [comment]
Sure I guess/hope the linting errors, should be solved. You squash the two commits or should I do it?

**Comment by davidplowman** [comment]
I'm happy to do it, but can you supply an email address I can use in a "Signed-off-by:" line? Thanks! (Or alternatively, you could squash them and add your sign-off.)

**Comment by Petros626** [comment]
> I'm happy to do it, but can you supply an email address I can use in a "Signed-off-by:" line? Thanks! (Or alternatively, you could squash them and add your sign-off.)

Still facing some errors, but I thought I solved them, maybe you can show how to do this correctly. The e-mail address is: petros.katsoulakos@web.de

**Comment by davidplowman** [comment]
Yes, isort frequently baffles me with its complaints. Often it's easiest just to run "python3 -m isort <problem-file>" and it fixes it for you! For the format string, it seems not to like the `{}`. Maybe use named-parameter sytle, or perhaps an f-string.

**Comment by davidplowman** [comment]
Actually let me do all that for you...

**Pull request closed without merging**
