### PR TITLE
Update opencv_face_detect.py

### PR DESCRIPTION
**Pull request by steveiliop56**
This script does not work with the new pi camera v3 module. This simple line of code fixes everything.

### CODE REVIEW

**Comment by edward-ardu** [comment]
It seems to be very similar to my previous state
https://github.com/raspberrypi/picamera2/pull/411#event-7855412829

**Comment by davidplowman** [comment]
Hi, thanks for this PR. In principle I'm happy enough to merge it, but I'm still puzzled why it sometimes seems to be necessary but for other folks (myself included) everything seems fine without it. Any ideas?

**Comment by raspberrydeveloper** [comment]
I am using raspberry pi os 64 bit. So maybe in 64 bit version of opencv it can't display the frames without a small delay that ``cv2.waitKey(1)`` offers?

**Comment by davidplowman** [comment]
I use the 64-bit OS too, so I don't really understand. Nonetheless I don't mind merging this PR, however, would you be able to resubmit it in accordance with our [guidelines](https://github.com/raspberrypi/picamera2#contributing)? I don't think there's much that needs tweaking: it needs to be a PR for the next rather than the main branch, as helpful a commit message as you can manage, and your "sign-off" at the bottom of this message. Thanks!

**Comment by steveiliop56** [comment]
Hi! I just saw the messages and I didn't understand the guide lines. I have to just add a signed of at the bottom of the comment where I describe the pull request? (Sorry for the delay...)

**Comment by davidplowman** [comment]
Hi, yes you would need to:

* Make it PR onto our "next" rather than "main" branch.
* Perhaps add a comment that explains what behaviour you have fixed.
* And add a sign-off.

Checking the format of other commits in the repository will probably help you. Thanks!

**Pull request closed without merging**
